version: '3'

services:
  apache:
    image: bitnami/apache:latest
    ports:
      - 8080:8080
    volumes:
      - ./web:/app

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./docker/mqtt:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001